# Generated by Django 2.1.7 on 2020-03-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='urlToImage',
            field=models.ImageField(default='img/None/no-img.jpg', upload_to='img/'),
        ),
    ]
