# Generated by Django 2.1.7 on 2020-03-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20200323_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='publishedAt',
            new_name='publishedat',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='urlToImage',
            new_name='urltoimage',
        ),
    ]
