# Generated by Django 2.1.7 on 2020-03-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0009_auto_20200323_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
